### ISSUE TITLE
Probable code error?

### ISSUE THREAD

**Issue by fb82** [xuy123456/fcgnn#2]
Hi,

I've found that during this code execution in `fcgnn.py`:

`def _map(idx,n):`
            
            id1 = idx.unsqueeze(1)
            id2 = idx.unsqueeze(2)
            
            relative_pos = id1 - id2
            b, l, c = idx.shape
            
            b_ids = torch.arange(0, b, device=id1.device).view(-1, 1).repeat(1, l*n).view(-1)
            l_ids = torch.arange(0, l, device=id1.device).view(-1, 1).repeat(1, b*n).view(-1)
            
            map = - (relative_pos**2).sum(dim=-1)

            if map.shape[1] > n:
                _, query = map.topk(k=n, dim=2, largest=True, sorted=True)
            else:
                _, query = map.topk(k=map.shape[1], dim=2, largest=True, sorted=True)

            return query, relative_pos[b_ids, l_ids, query.view(-1), :].reshape(b, l, n*4)

in case  `map.shape[1] < n` the length for the index lists `b_ids`, `l_ids` and `query.view(-1)` for `relative_pos[b_ids, l_ids, query.view(-1), :]` mismatch so I get errors. Is it right to modify the code as it follows?

`def _map(idx, n):`

            id1 = idx.unsqueeze(1)
            id2 = idx.unsqueeze(2)
            
            relative_pos = id1 - id2
            b, l, c = idx.shape
                        
            map = - (relative_pos**2).sum(dim=-1)

            if map.shape[1] > n:
                _, query = map.topk(k=n, dim=2, largest=True, sorted=True)
            else:
                _, query = map.topk(k=map.shape[1], dim=2, largest=True, sorted=True)
                n = map.shape[1]

            b_ids = torch.arange(0, b, device=id1.device).view(-1, 1).repeat(1, l*n).view(-1)
            l_ids = torch.arange(0, l, device=id1.device).view(-1, 1).repeat(1, b*n).view(-1)

            return query, relative_pos[b_ids, l_ids, query.view(-1), :].reshape(b, l, n*4)

Thanks,
Fabio

**Comment by fb82** [comment]
Actually I got a further error next in the code, so I thinkthe best way is to not perform FC-GNN when the number of matches is less or equal to `n=8`

**Comment by xuy123456** [comment]
Thanks for pointing out! We rearrange the code so that it can work for n<8 now.

**Comment by fb82** [comment]
Thanks!
